os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.1

sudo: required

language: c

addons:
  apt:
    packages:
    - gcc
    - gfortran
    - autotools-dev
    - libtool
    - gtk-doc-tools
    - gobject-introspection
    - gir1.2-glib-2.0
    - libgirepository1.0-dev
    - pkg-config
    - libglib2.0-dev
    - libgmp3-dev
    - libmpfr-dev
    - libfftw3-dev
    - libcfitsio3-dev
    - libsundials-serial-dev
    - libnlopt-dev
    - texlive
    - texlive-bibtex-extra
    - texlive-science
    - texlive-publishers
    - tex4ht
    - perl
    - libxml-libxml-perl

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CONFDOCS="--enable-man --enable-gtk-doc"                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tsvetko.tsvetkov/trusty-backports ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgsl-dev                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then hash -r                                         ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then softwareupdate --list                           ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew upgrade python                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc                                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew link gcc                                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gobject-introspection              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gsl gtk-doc gmp mpfr               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install fftw cfitsio                       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install sundials --without-suite-sparse    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then /usr/bin/yes | pip2 uninstall numpy             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install numpy --without-python             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install nlopt                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then for gcc_name in gcc gcc-4 gcc-5 gcc-6 gcc-7 gcc-8; do loc=$($gcc_name --version); if test $? = 0; then export CC=$gcc_name; echo $loc; fi ; done ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:${PKG_CONFIG_PATH}"                                                                  ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export LDFLAGS="-lklu"                          ; fi
  - NOCONFIGURE=yes ./autogen.sh

script:
  - "./configure $CONFDOCS"
  - cat config.log
  - make
  - make check
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make dist ; fi

#deploy:
#  provider: releases
#  api_key:
#    secure: ZtGqjolvjQ3RAbj+inJZxAs3WnZrguryO68bjRZ0N0VfxmhNVhgJ4i3uXVTCnfiX5avIsm2HgnJfuXzag/FI3dSRTv8++iC68VrxJnQtrrRHSmKIBBDFMbVbJJFmlQfpsnwaH1LzByj90kZpDH4qJJrK1KeFRDhTy8yG20FShw+ieklxdUmeCHlWusWMkkBGfFJ4xB+rthtEIVvJ/HXAl1wATwCdruB1CPIYHMReqIQpHPMhipYHtHW8/K56tAVytcPslQl0Jdxhe9KPiZZANvxolME7i+jkRVjIwI6X2tR4+D7matST2pGDwMk5wrX3i1masXIIYktCByuCh1oICCfTI6BL/xhwqBAAEzoPEI+OI1QH/KOoyJxs0/X0yFBLJ+UdseQVTCzdajCExU1h5kWkS6QrMm8RPV02V6iZwYI5fwMWlPCQdVbQZRhSuE/bf2jEezGKznQYWOSP11cjjrmhyg+JSNBS69LlTb2sLy/a/CV37Op0MTahLMmOv/DwXvluAgPsSrcUZcNR7NU2V+cNh6E6cB44OQqH1fV7fXDs3yV4Bjwlx572rKy7+Yo640f4Sn2NFHD5U9yE+4h9mYmfxaSQmgyjqcZH86FAgYVMWWPKrGOr10w+I8kRw6tZud9j4cdV3w8QnBy9Nybk1xho9hlCpFX/Om0mQfZmrC4=
#  file: numcosmo-0.14.1.tar.gz
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: NumCosmo/NumCosmo
# removed deploy
