---
name: numcosmo_developer
channels:
  - conda-forge
  - nodefaults
dependencies:
  - astropy
  - black
  - c-compiler
  - cfitsio
  - click
  - coverage
  - fftw
  - flake8
  - fortran-compiler
  - gcovr
  - getdist
  - gi-docgen
  - glib
  - glib-tools
  - gmp
  - gobject-introspection
  - gsl
  - hdf5
  - jupyter
  - lcov
  - libflint
  - libfyaml
  - matplotlib-base
  - meson
  - mpfr
  - mypy
  - ninja
  - nlopt
  - numpy < 2.4
  - openblas=*=*openmp*
  - openmpi
  - pandas
  - pip
  - pip:
      - pygobject-stubs
      - pytest-tap
      - types-tabulate
  - plotnine < 0.15
  - pyccl >= 3.0.0
  - pydantic
  - pygobject
  - pylint
  - pytest
  - pytest-cov
  - pytest-lazy-fixtures
  - python >= 3.11
  - quarto
  - rich
  - scipy
  - setuptools
  - tabulate
  - tqdm
  - typer
  - zlib
